version: '3'

services:
  redis-master:
    image: redis:latest
    container_name: redis-master
    ports:
      - "6379:6379"

  redis-replica:
    image: redis:latest
    container_name: redis-replica
    ports:
      - "6380:6379"
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - redis-master

  mongo:
    image: mongo
    restart: always #コンテナが何らかの理由で終了した場合、必ず再起動する
    ports:
      - 8081:8081
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db:/data/db
      - ./configdb:/data/configdb
