name: Check Test

on:
  workflow_dispatch:
  push:
    branchs:
      - master
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: <TAG>
          cache-from: type=gha
          cache-to: type=gha,mode=max

    - name: Deploy to server
        run: |
          ssh your-server "docker pull your-dockerhub-username/your-repo-name:latest && docker run -d -p 8080:8080 your-dockerhub-username/your-repo-name:latest"
        env:
          SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
