name: Check Test

on:
  push:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
        
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Launch services
        run: docker-compose up -d

      - name: Install wait-for-it
        run: |
          wget https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
          chmod +x wait-for-it.sh
          
      - name: Wait for MongoDB and Redis
        run: |
          ./wait-for-it.sh localhost:27017 --timeout=60
          ./wait-for-it.sh localhost:6379 --timeout=60
          ./wait-for-it.sh localhost:6380 --timeout=60

      - name: Install Packages
        run: npm ci
        working-directory: server

      - name: Run Test
        run: npm run test
        working-directory: server

